[profile.default]
# solc_version = "^0.8.26"
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink = lib/chainlink-brownie-contracts","@openzeppelin =lib/openzeppelin-contract"]

[invariant]
runs = 128
depth = 128
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
